### ISSUE TITLE
Adding Sidebar

### ISSUE THREAD

**Issue by tani** [nenbutsu/ISLispHyperDraft#1]
Thank you for great works.
In these days, I read the draft with this version which has enough hyperlinks and good style-sheet to read it with the modern web browsers. And I propose to  add a fixed sidebar to read it more efficiently. Now I have [the version](https://github.com/ta2gch/ISLispHyperDraft) to add the sidebar.  Would you like to merge this? Sadly, It might be changed the order of contents to read in emacs. Please tell me your opinion.
Regards.

**Comment by nenbutsu** [comment]
Mr. Taniguchi, thank you for your offer. Definitely I accept the change. 
I'm new to git system, so could you lead the way to merge your work?

**Comment by nenbutsu** [comment]
I just offered you an invitation to the project. Is this enough?

**Comment by nenbutsu** [comment]
OK. I adopted your work and the web site http://minejima.jp/ISLispHyperDraft/islisp-v23.html is also updated.

**Comment by tani** [comment]
I appreciate to your acceptation. 
You could merge my works without an invitation because Github has Pull Request system. Of cause I was grad to became an member of this project.
You said you are new to git system.  I recommend to use Pull Request system in this time. How about you?

**Comment by nenbutsu** [comment]
OK, first you give me a pull request?

**Comment by nenbutsu** [comment]
Or, should I issue a pull request?

**Comment by tani** [comment]
I'll do soon. Please wait 30 seconds.

**Comment by tani** [comment]
I have done. Now you can merge my works.

**Comment by nenbutsu** [comment]
I just merged your work. Thank you for your support. 
And the side bar is so cool. I must've added one if I didn't forget the CSS.

**Comment by tani** [comment]
No problem because I needs it too. 
CSS3 became more complex than before.

**Comment by tani** [comment]
I'm looking forward to your implementation KISS. Cheers.
