### ISSUE TITLE
Iris makes examples editable and executable.

### ISSUE THREAD

**Issue by tani** [nenbutsu/ISLispHyperDraft#5]
Hi, Mr. Minejima. I'm glad for your improving project.

As you know, I have an ISLisp implementation which works on JavaScript VMs. I propose the collaboration with my implementation. Please see [this](https://jsfiddle.net/s4mpch0z/).
This features are good for the beginners of ISLisp.

To apply this to your project, I request you to change examples. It is not easy, too hard.
So this is feature requests (this is double means). How about it?

**Comment by nenbutsu** [comment]
Hi, Mr. ta2gch. Looks nice. Although I don't get completely how things work.
Is all I have to do adding some tags to HyperDraft's examples like the following?

＜input id="input" value="(+ 1 1)"＞
＜button id="eval"＞⇒＜/button＞
＜span id="output"＞2＜/span＞

**Comment by tani** [comment]
Okey, I introduce you `islisp.eval`. This function gets `string` and returns `string`.
That snippets has three parts.

1.  Gets string from some textbox (`textarea` or `input`)
2. Evaluates string with `islisp.eval`
3. Sets string returned by `islisp.eval`

To apply that snippets, please give me a few hours. I have an idea.

**Comment by tani** [comment]
@nenbutsu I have new version of that. Please see [this](https://jsfiddle.net/wz0eb1ko/).
The old uses `id`,  but the new uses `class` and brothers selection to apply in multiple elements.
Now you can use it like this in your project.

In the last of `<body>`,
```
<script src="https://islisp.js.org/api/eval.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script>
$(".eval").on("click", function(e){
	var s = $(e.target).prev().val()
	$(e.target).next().html(islisp.eval(s))
})
</script>
```
and all of examples makes,

```
＜input class="input" value="(+ 1 1)"＞
＜button class="eval"＞⇒＜/button＞
＜span class="output"＞2＜/span＞
```

Cheers.

**Comment by nenbutsu** [comment]
Thanks!
I just added one example. Please see the following page, 
http://minejima.jp/ISLispHyperDraft/islisp-v23.html#cons
and tell me what you think of it.

**Comment by tani** [comment]
It's awesome!
In my feeling, The duplicates (plain text and editables) are not better than before. Would you like to reduce the duplicates too? In my examples, `<span class=".output">` has default value like this,

```
＜input class="input" value="(+ 1 1)"＞
＜button class="eval"＞⇒＜/button＞
＜span class="output"＞2＜/span＞
```

In this way, you can remove plain text examples.

...Oops, In my solution we cannot read in emacs.

```
<span class="input" contenteditable="true">(+ 1 1)</span>
<button class="eval">⇒</button>
<span class="output">2</span>
```

Okey. Now you can use this draft in emacs. This is a `<input>` free version.
Would you like to reduce duplicates?

**Comment by nenbutsu** [comment]
Looks like that's where we should go.
http://minejima.jp/ISLispHyperDraft/islisp-v23.html#cons

But currently the button emits #<END-OF-STREAM >, is this something you can fix on your part?

**Comment by tani** [comment]
Excuse me, please change `val()` to `html()`.
I guess this change fix the problem.

**Comment by nenbutsu** [comment]
Thanks for the fix.
I really love this gimmick.
Now, I'll add these tags to all the examples.

**Comment by tani** [comment]
No problem. I and all of Iris users will visit your page because I added a hyperlink in my project page. So the improving of your project effects my project too.  I, however, notice you a few of examples will not work because Iris doesn't support completely as ISLisp. To fix it, I do my best. Thank you.
