### ISSUE TITLE
The table of Special Operator 'CONVERT' is broken.

### ISSUE THREAD

**Issue by tani** [nenbutsu/ISLispHyperDraft#7]
In your draft I found a broken table element. Could you fix it? Thank you.

The following picture will be deleted after a month because of the rule of screenshots.firefox.com.

![](https://screenshots.firefoxusercontent.com/images/c3ebb60c-c6fa-45a7-a0b2-22cb7686cb6e.png)

**Comment by nenbutsu** [comment]
Thanks for the report! I'll fix it soon.

**Comment by nenbutsu** [comment]
OK, I've fixed the bug and committed, pushed and update the website.

**Comment by tani** [comment]
Thank you so much!
